apiVersion: v1
entries:
  blas-jet:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-11T12:54:35.413475532Z"
    description: A Helm chart for Kubernetes
    digest: e410b8f5c67ba6163cf89d54311c9c58a0d46c31a2c1c3e4615f635fa19c530b
    name: blas-jet
    type: application
    urls:
    - https://vinhdat4999.github.io/blas-helm/charts/blas-jet/blas-jet-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-11T12:54:35.412553601Z"
    description: A Helm chart for Kubernetes
    digest: 4d6bbd3f8f8336168498e20b5bb23afb2cbcc7385e3c48cd375614a1188598b1
    name: blas-jet
    type: application
    urls:
    - https://vinhdat4999.github.io/blas-helm/charts/blas-jet/blas-jet-2.2.0.tgz
    version: 2.2.0
generated: "2024-11-11T12:54:35.411260253Z"
