apiVersion: v1
entries:
  blas-service-support:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-11T12:53:36.309628144Z"
    description: A Helm chart for Kubernetes
    digest: b6aa8c3072ec19edd3d9ca1ec24db146a361cd81908f1d36de23f38c0fa4f304
    name: blas-service-support
    type: application
    urls:
    - https://vinhdat4999.github.io/blas-helm/charts/blas-service-support/blas-service-support-3.2.0.tgz
    version: 3.2.0
generated: "2024-11-11T12:53:36.307773368Z"
