apiVersion: v1
entries:
  blas-notification:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-11T11:36:18.330514512Z"
    description: A Helm chart for Kubernetes
    digest: b91ae9d166d6f45da903af4d322df6afcec02ebb9b62aadd6cbc0e61d517aff8
    name: blas-notification
    type: application
    urls:
    - https://vinhdat4999.github.io/blas-helm/charts/blas-notification/blas-notification-5.1.0.tgz
    version: 5.1.0
generated: "2024-11-11T11:36:18.328804589Z"
